<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-08-27 19:02
=======
# Generated by Django 2.2.4 on 2019-08-24 02:39
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21

import django.contrib.postgres.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField()),
                ('post_tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), null=True, size=None)),
                ('post_pic', models.CharField(max_length=200)),
            ],
        ),
    ]
