# Generated by Django 2.2.4 on 2019-08-24 20:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuanime', '0003_auto_20190824_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
    ]
