# Generated by Django 2.2.4 on 2019-08-24 20:35

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sfuanime', '0005_auto_20190824_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce_4.fields.TinyMCEModelField(verbose_name='Foo Content')),
            ],
        ),
    ]
